### ISSUE TITLE
.p8.png compiler?

### ISSUE THREAD

**Issue by dylanmc** [dansanderson/picotool#1]
It would be nice to be able to write Pico-8 programs with my laptop editor, and compile them to .p8.png's

This is great - thanks!

**Comment by felipebueno** [comment]
:+1: @dansanderson  this feature would be really awesome :smile:

**Comment by dansanderson** [comment]
The picotool API now has support for saving .p8.png carts. writep8, luamin, luafmt, and the new build tool can all take either .p8 or .p8.png filenames. For p8tool build, if the output file does not exist, a new cart with an empty label is created, otherwise the existing label is reused.

To-do: documentation updates, maybe more options for build about labels (e.g. take a label from a different cart, or generate one somehow).
